version: '3'

services:
  automated-nginx-demo:
    image: scubakay/automated_nginx_demo:latest
    expose:
      - 80
    environment:
      VIRTUAL_HOST: 136.144.216.182
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
