version: '3'

services:
  automated-nginx-demo:
    image: scubakay/automated_nginx_demo:latest
    environment:
      VIRTUAL_HOST: 136.144.216.182, www.136.144.216.182
      VIRTUAL_PORT: 80
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
