version: '3'

services:
  automated-nginx-demo:
    image: scubakay/automated_nginx_demo:master
    expose:
      - 80
    ports:
      - "80:80"
    environment:
      VIRTUAL_HOST: http://demo.136.144.216.182/
      VIRTUAL_PORT: 80

networks:
  default:
    external:
      name: nginx-proxy
